global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
accesslog:
  format: json

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

#certificatesResolvers:
  letsencrypt:
    acme:
      email: stendton@gmail.com
      storage: /var/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    network: web
  file:
    directory: /etc/traefik
    watch: true